"""Recreate tables with foreign keys

Revision ID: 59dbdf3dc655
Revises: 
Create Date: 2024-07-25 11:51:23.597547

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '59dbdf3dc655'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.alter_column('fund_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('instrument_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.alter_column('instrument_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('fund_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
